export const AppImage = {
  home: require('./home.png'),
  homeFilled: require('./homeFilled.png'),
  category: require('./category.png'),
  categoryFilled: require('./categoryFilled.png'),
  heart: require('./menuHeart.png'),
  menu: require('./menu.png'),
  bag: require('./bag.png'),
  search: require('./search.png'),
  placeholder: require('./placeholder.png'),
  placeholderDark: require('./placeholderDark.png'),
  fillHeart: require('./fillHeart.png'),
  emptyHeart: require('./heart.png'),
  add: require('./add.png'),
  backArrow: require('./backArrow.png'),
};
